### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all_next'

### ISSUE THREAD

**Issue by Pheenoh** [aws-samples/rds-extended-support-cost-estimator#5]
https://github.com/aws-samples/rds-extended-support-cost-estimator/blob/d6f4eca4f50c55a77c384448ce6b0aa634361991/scripts/utils/rds_mappings.py#L111

This url for the documentation that's being parsed here was updated recently, breaking the script entirely:

```bash
python find_rds_extended_support_instances.py -h
```

```bash
Traceback (most recent call last):
  File "/home/ec2-user/rds-extended-support-cost-estimator/scripts/find_rds_extended_support_instances.py", line 55, in <module>
    DB_INSTANCE_MAPPING = get_rds_instance_mapping()
  File "/home/ec2-user/rds-extended-support-cost-estimator/scripts/utils/rds_mappings.py", line 123, in get_rds_instance_mapping
    mappings_section_tables = mappings_section.find_all_next("table")
AttributeError: 'NoneType' object has no attribute 'find_all_next'
```

I was able to get around it by updating the url to an older version of the page, but the logic pulling the mappings here should probably be updated to something more immutable than HTML parsing.

**Comment by minhlong94** [comment]
This happened to me as well. After reading the code I also confirm that the reason is because of instead of static website, they now use drop-down, which makes the code unable to parse the HTML.

**Comment by playphil** [comment]
Perhaps these can be parsed now from URL https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.Summary.html

**Comment by sin-ak** [comment]
Thanks for flagging this - i'll work on fixing the issue and update soon.

**Comment by sin-ak** [comment]
Temporarily pushed a fix - updated the URL and the HTML scrapping dom ID. 

TODO - Fix the logic to get rds instance mapping in a more reliable way. The HTML of the AWS Documentation that was being scraped
    previously has changed, causing the script to fail. There are 2 approaches to repalce the current HTML scrapping logic: 
    1/  either use a hard coded file with list of rds instances and vCPU mapping, as these mappings are static and do not change. Will need to handle the condition of new instance types/family/size getting added in future, for which see pt 2 below.
    2/ Use the AWS Pricing API to retrive the vCPU details for an instance, and build a cache locally to avoid calling the API repeatedly. This can also be used in conjunction with pt 1 above. In case an instance type is not found in the hardcoded file, then call the pricing API and update the mappings file and write back for future usage. 
        AWS Pricing API CLI command example: 
        `aws pricing get-products --service-code AmazonRDS --region us-east-1 --filters Type=TERM_MATCH,Field=UsageType,Value=USW2-InstanceUsage:db.m5.large Type=TERM_MATCH,Field=Operation,Value=CreateDBInstance:0002`
